# Generated by Django 4.1 on 2022-08-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='user_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QrType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50, null=True)),
                ('is_dynamic', models.BooleanField(blank=True, default=True)),
                ('img', models.ImageField(upload_to='media/qrcodes')),
                ('input_url', models.URLField(blank=True, max_length=255, null=True)),
                ('action_url', models.URLField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('web', 'Website URL'), ('tex', 'Text'), ('pdf', 'PDF'), ('biz', 'Business Card'), ('wap', 'Whatsapp'), ('img', 'Image'), ('eml', 'Email'), ('eve', 'Events')], max_length=3)),
                ('scan_count', models.IntegerField(blank=True, default=None, null=True)),
                ('date_gen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrgen.file')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrgen.qrtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
