# Generated by Django 4.1 on 2022-08-22 15:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='date_gen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='img',
            field=models.ImageField(upload_to='qrcodes/'),
        ),
    ]
