# Generated by Django 4.0.5 on 2022-08-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0002_qrcode_action_url_qrcode_input_url_qrcode_scan_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_dynamic',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
